using System.ComponentModel.DataAnnotations;

namespace NsUserManager.Models
{
    public class AddScimUser : IValidatableObject
    {
        public string UserName { get; set; } = string.Empty;
        public string ExternalId { get; set; } = string.Empty;
        [Required]
        public string Email { get; set; } = string.Empty;
        [Required]
        public string GivenName { get; set; } = string.Empty;
        [Required]
        public string FamilyName { get; set; } = string.Empty;

        public bool Active { get; set; } = true;

        public bool IsExternalIdAutogenerated { get; set; } = true;
        public bool IsUsernameAutogenerated { get; set; } = true;

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (!IsExternalIdAutogenerated && string.IsNullOrWhiteSpace(ExternalId))
            {
                yield return new ValidationResult("External Id is required when not autogenerated.", new[] { nameof(ExternalId) });
            }

            if (!IsUsernameAutogenerated && string.IsNullOrWhiteSpace(UserName))
            {
                yield return new ValidationResult("Username is required when not autogenerated.", new[] { nameof(UserName) });
            }
        }
    }
}
